name: Zeph's Blog
author: Brynley McDonald
url: http://zephire.nz
excerpt_separator: "<!--more-->"
encoding: utf-8
exclude: ["Gemfile", "Gemfile.lock", "init.go"]
include: [".well-known"]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5
paginate_path: "/page/:num"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-autoprefixer
sass:
  style: compressed