name: Zeph's Blog
author: Brynley McDonald
url: http://zephire.nz
excerpt_separator: "<!--more-->"
encoding: utf-8
exclude: [".gitignore", ".git", "Gemfile"]
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5
paginate_path: "/page/:num"
gems:
- jekyll-paginate
- autoprefixer-rails
- sass
- font-awesome-sass
- bootstrap
- jekyll-assets
- uglifier
- jekyll-sitemap
assets:
  digest: false
  
